(fiasco:define-test-package #:mahogany-tests/tree
  (:local-nicknames (#:tree #:mahogany/tree))
  (:use #:mahogany/wm-interface
        #:mahogany/test/util))

(in-package #:mahogany-tests/tree)

(defstruct (mock-output (:include mahogany/core:output)))

(defun container-add-mock-output (container
                                  &key (x 0) (y 0) (width 100) (height 100))
  (cl-mock:dflet ((hrt:output-position
                     (output)
                     (declare (ignore output))
                     (values x y))
                    (hrt:output-resolution
                     (output)
                     (declare (ignore output))
                     (values width height)))
    (tree:tree-output-add container (make-instance 'tree:output-container
                                                   :output
                                                   (make-mock-output)))))

(defun make-tree-for-tests (&key (x 0) (y 0) (width 100) (height 100))
  (let ((container (make-instance 'tree:layer-container
                                  :hrt-layer (cffi:null-pointer))))
    (multiple-value-bind (output-node frame)
        (container-add-mock-output container :x x :y y :width width :height height)
      (values frame output-node container))))

(defun make-tree-frame (children &key split-direction (x 0) (y 0) (width 100) (height 100))
  (let ((parent (make-instance  'tree:tree-frame
                                :x x :y y
                                :width width :height height
                                :split-direction split-direction)))
    (dolist (c children)
      (setf (tree:frame-parent c) parent))
    (setf (tree:tree-children parent) children)
    parent))

(defmacro with-border-box-mocks (() &body body)
  `(cl-mock:dflet ((hrt::border-box-create
                    (layer style x y width height)
                    (declare (ignore layer style x y width height))
                    (cffi:null-pointer))
                   (hrt:hrt-border-box-set-relative
                    (box x y)
                    (declare (ignore box x y)))
                   (hrt:hrt-border-box-set-enabled
                    (box enabled)
                    (declare (ignore box enabled)))
                   (hrt:hrt-border-box-destroy
                    (box)
                    (declare (ignore box)))
                   (hrt:hrt-border-box-set-size
                    (box width height)
                    (declare (ignore box width height))))
     ,@body))

(fiasco:deftest set-position-view-frame ()
  (with-border-box-mocks ()
    (let ((tree (make-tree-for-tests :x 0 :y 0)))
      (set-position tree 100 200)
      (is (= (tree:frame-x tree) 100))
      (is (= (tree:frame-y tree) 200)))))

(defun %initialize-family (layer parent &rest children)
  (loop for c in children
        do (setf (tree:frame-parent c) parent))
  (setf (tree:frame-parent parent)
        layer))

(defmacro with-tree ((parent-spec &rest child-specs) &body body)
  (let ((container-name (gensym "layer-container"))
        (parent-var (car parent-spec))
        (child-vars (mapcar #'car child-specs)))
    (flet ((make-construction-call (spec)
             (destructuring-bind (&key x y width height view) (cdr spec)
               (list (car spec)
                     `(make-instance 'tree:view-frame :x ,x :y ,y
                                                      :view ,view
                                                      :width ,width
                                                      :height ,height
                                                      :parent ,container-name)))))
      (let* ((children (mapcar #'make-construction-call child-specs))
             (parent `(,parent-var
                       (make-tree-frame (list ,@child-vars) ,@(cdr parent-spec)))))
        `(let* ((,container-name (make-instance 'tree:layer-container
                                                :children nil
                                                :hrt-layer (cffi:null-pointer)))
                ,@children
                ,parent)
           (%initialize-family ,container-name ,parent-var ,@child-vars)
           ,@body)))))

(fiasco:deftest set-position-tree-frame ()
  (with-border-box-mocks ()
    (with-tree ((parent :split-direction :horizontal)
                (child-1 :x 0 :y 0 :width 50 :height 100)
                (child-2 :x 51 :y 0 :width 50 :height 100))
      (set-position parent 100 200)
      (is (= (tree:frame-x child-1) 100))
      (is (= (tree:frame-y child-1) 200))
      (is (= (tree:frame-x child-2) 151))
      (is (= (tree:frame-y child-2) 200)))))

(fiasco:deftest setf-frame-x-view-frame-sets-value ()
  (with-border-box-mocks ()
    (let ((tree (make-tree-for-tests :x 0 :y 0)))
      (setf (tree:frame-x tree) 100)
      (is (= 100 (tree:frame-x tree))))))

(fiasco:deftest setf-frame-y-view-frame-sets-value ()
  (with-border-box-mocks ()
    (let ((tree (make-tree-for-tests :x 0 :y 0)))
      (setf (tree:frame-y tree) 223)
      (is (= (tree:frame-y tree) 223)))))

(fiasco:deftest setf-frame-y-tree-frame ()
  (with-border-box-mocks ()
    (with-tree ((parent  :split-direction :horizontal)
                (child-1 :x 0 :y 0 :width 50 :height 100)
                (child-2  :x 51 :y 0 :width 50 :height 100))
      (setf (tree:frame-y parent) 100)
      (is (= (tree:frame-x parent) 0))
      (is (= (tree:frame-y parent) 100))
      (is (= (tree:frame-x child-1) 0))
      (is (= (tree:frame-y child-2) 100))
      (is (= (tree:frame-x child-2) 51)))))

(fiasco:deftest setf-frame-x-tree-frame ()
  (with-border-box-mocks ()
    (with-tree ((parent :split-direction :horizontal)
                (child-1 :x 0 :y 0 :width 50 :height 100)
                (child-2 :x 51 :y 0 :width 50 :height 100))
      (setf (tree:frame-x parent) 100)
      (is (= (tree:frame-x parent) 100))
      (is (= (tree:frame-y parent) 0))
      (is (= (tree:frame-x child-1) 100))
      (is (= (tree:frame-y child-2) 0))
      (is (= (tree:frame-x child-2) 151)))))

(fiasco:deftest setf-frame-width-view-frame ()
  (with-border-box-mocks ()
    (let ((tree (make-tree-for-tests :x 10 :y 15 :width 100 :height 100)))
      (setf (tree:frame-width tree) 40)
      (is (= (tree:frame-width tree) 40))
      (is (= (tree:frame-height tree) 100)))))

(fiasco:deftest setf-frame-height-view-frame ()
  (with-border-box-mocks ()
    (let ((tree (make-tree-for-tests :x 10 :y 15 :width 100 :height 100)))
      (setf (tree:frame-height tree) 40)
      (is (= (tree:frame-height tree) 40))
      (is (= (tree:frame-width tree) 100)))))

(fiasco:deftest setf-frame-width-horizontal-tree-frame ()
  (with-border-box-mocks ()
    (with-tree ((parent :x 25 :y 15 :split-direction :horizontal)
                (child-1 :x 25 :y 15 :width 50 :height 100)
                (child-2 :x 75 :y 15 :width 50 :height 100))
      (setf (tree:frame-width parent) 50)
      (is (= (tree:frame-height parent) 100))
      (is (= (tree:frame-height child-1) 100))
      (is (= (tree:frame-height child-2) 100))
      (is (= (tree:frame-width parent) 50))
      (is (= (tree:frame-width child-1) 25))
      (is (= (tree:frame-width child-2) 25))
      (is (= (tree:frame-x child-1) 25))
      (is (= (tree:frame-x child-2) 50))
      (is (= (tree:frame-y child-1) 15))
      (is (= (tree:frame-y child-2) 15)))))

(fiasco:deftest setf-frame-width-vertical-tree-frame ()
  (with-border-box-mocks ()
    (with-tree ((parent :x 25 :y 15 :split-direction :vertical)
                (child-1 :x 25 :y 15 :width 100 :height 50)
                (child-2 :x 25 :y 65 :width 100 :height 50))
      (setf (tree:frame-width parent) 50)
      (is (= (tree:frame-height parent) 100))
      (is (= (tree:frame-height child-1) 50))
      (is (= (tree:frame-height child-2) 50))
      (is (= (tree:frame-width parent) 50))
      (is (= (tree:frame-width child-1) 50))
      (is (= (tree:frame-width child-2) 50))
      (is (= (tree:frame-x child-1) 25))
      (is (= (tree:frame-x child-2) 25))
      (is (= (tree:frame-y child-1) 15))
      (is (= (tree:frame-y child-2) 65)))))

(fiasco:deftest setf-frame-height-vertical-tree-frame ()
  (with-border-box-mocks ()
    (with-tree ((parent :x 25 :y 15 :split-direction :vertical)
                (child-1 :x 25 :y 15 :width 100 :height 50)
                (child-2 :x 25 :y 65 :width 100 :height 50))
      (setf (tree:frame-height parent) 50)
      (is (= (tree:frame-width parent) 100))
      (is (= (tree:frame-width child-1) 100))
      (is (= (tree:frame-width child-2) 100))
      (is (= (tree:frame-height parent) 50))
      (is (= (tree:frame-height child-1) 25))
      (is (= (tree:frame-height child-2) 25))
      (is (= (tree:frame-x child-1) 25))
      (is (= (tree:frame-x child-2) 25))
      (is (= (tree:frame-y child-1) 15))
      (is (= (tree:frame-y child-2) 40)))))

(fiasco:deftest setf-frame-height-horizontal-tree-frame ()
  (with-border-box-mocks ()
    (with-tree ((parent  :x 25 :y 15 :split-direction :horizontal)
                (child-1 :x 25 :y 15 :width 100 :height 50)
                (child-2 :x 25 :y 65 :width 100 :height 50))
      (setf (tree:frame-height parent) 50)
      (is (= (tree:frame-width parent) 100))
      (is (= (tree:frame-width child-1) 100))
      (is (= (tree:frame-width child-2) 100))
      (is (= (tree:frame-height parent) 50))
      (is (= (tree:frame-height child-1) 25))
      (is (= (tree:frame-height child-2) 25))
      (is (= (tree:frame-x child-1) 25))
      (is (= (tree:frame-x child-2) 25))
      (is (= (tree:frame-y child-1) 15))
      (is (= (tree:frame-y child-2) 65)))))

(fiasco:deftest single-frame--frame-at-test ()
  (with-border-box-mocks ()
    (let ((frame (make-instance 'tree:frame :x 0 :y 0 :width 100 :height 100)))
      (is (equal frame (tree:frame-at frame 50 50)))
      (is (not (tree:frame-at frame -1 50)))
      (is (not (tree:frame-at frame 50 -1)))
      (is (not (tree:frame-at frame -1 -1))))))

(fiasco:deftest set-dimensions-frame ()
  (with-border-box-mocks ()
    (let ((frame (make-instance 'tree:frame :x 0 :y 0 :width 100 :height 100)))
      (set-dimensions frame 400 200)
      (is (= (tree:frame-width frame) 400))
      (is (= (tree:frame-height frame) 200)))))

(fiasco:deftest set-dimensions-tree-frame-width-change ()
  (with-border-box-mocks ()
    (with-tree ((parent :height 100 :width 100 :split-direction :horizontal)
                (child-1  :x 0 :y 0 :width 50 :height 100)
                (child-2  :x 50 :y 0 :width 50 :height 100))
      (set-dimensions parent 200 400)
      (is (= (tree:frame-width parent) 200))
      (is (= (tree:frame-height parent) 400))
      (is (= (tree:frame-width child-1) 100))
      (is (= (tree:frame-height child-1) 400))
      (is (= (tree:frame-width child-2) 100))
      (is (= (tree:frame-height child-2) 400)))))

(fiasco:deftest set-dimensions-tree-frame-height-change ()
  (with-border-box-mocks ()
    (with-tree ((parent :height 100 :width 100
                        :split-direction :vertical)
                (child-1 :x 0 :y 0 :width 100 :height 50)
                (child-2 :x 0 :y 50 :width 100 :height 50))
      (set-dimensions parent 200 400)
      (is (= (tree:frame-width parent) 200))
      (is (= (tree:frame-height parent) 400))
      (is (= (tree:frame-width child-1) 200))
      (is (= (tree:frame-height child-1) 200))
      (is (= (tree:frame-width child-2) 200))
      (is (= (tree:frame-height child-2) 200)))))

(fiasco:deftest set-dimensions-tree-frame-chidren-move-x ()
  (with-border-box-mocks ()
    (with-tree ((parent :height 100 :width 100
                        :split-direction :horizontal)
                (child-1 :x 0 :y 0 :width 50 :height 100)
                (child-2 :x 50 :y 0 :width 50 :height 100))
      (set-dimensions parent 200 400)
      (is (= (tree:frame-x parent) 0))
      (is (= (tree:frame-y parent) 0))
      (is (= (tree:frame-x child-1) 0))
      (is (= (tree:frame-y child-1) 0))
      (is (= (tree:frame-x child-2) 100))
      (is (= (tree:frame-y child-2) 0)))))

(fiasco:deftest set-dimensions-tree-frame-chidren-move-y ()
  (with-border-box-mocks ()
    (with-tree ((parent :x 20 :y 0 :height 100 :width 100
                        :split-direction :vertical)
                (child-1 :x 20 :y 0 :width 100 :height 50)
                (child-2 :x 20 :y 50 :width 100 :height 50))
      (set-dimensions parent 200 400)
      (is (= (tree:frame-x parent) 20))
      (is (= (tree:frame-y parent) 0))
      (is (= (tree:frame-x child-1) 20))
      (is (= (tree:frame-y child-1) 0))
      (is (= (tree:frame-x child-2) 20))
      (is (= (tree:frame-y child-2) 200)))))

(defun check-size (original-size frames accessor)
  "Ensure that the given frames add up to the original size"
  (let ((sum 0))
    (dolist (item frames)
      (let ((value (funcall accessor item)))
        (setf sum (+ sum value))))
    (is (= sum original-size) "Frame keeps original size of ~S (found ~S)" original-size sum)))

(defun poly-split-dim-test (repeats tree split-function accessor)
  (dotimes (i repeats)
    (let ((original-size (funcall accessor tree)))
      (multiple-value-bind (frame parent) (funcall split-function tree)
        (declare (ignore frame))
        (check-size original-size
                    (tree:tree-children parent) accessor)
        (setf tree parent)))))

(fiasco:deftest poly-split-frame-vertical-retains-total-dimensions ()
  (with-border-box-mocks ()
    (let ((tree:*new-split-type* :many))
      (multiple-value-bind (tree container) (make-tree-for-tests)
        (declare (ignore container))
        (poly-split-dim-test 4 tree #'tree:split-frame-v #'tree:frame-height)))))

(fiasco:deftest poly-split-frame-vertical-replaces-parent ()
  (with-border-box-mocks ()
    (let ((tree:*new-split-type* :many))
      (multiple-value-bind (tree container) (make-tree-for-tests)
        (multiple-value-bind (frame parent) (tree:split-frame-v tree)
          (declare (ignore frame))
          (is (find parent (tree:tree-children container) :test #'equal)))))))

(fiasco:deftest poly-split-frame-horizontal-retains-total-dimensions ()
  (with-border-box-mocks ()
    (let ((tree:*new-split-type* :many))
      (multiple-value-bind (tree container) (make-tree-for-tests)
        (declare (ignore container))
        (poly-split-dim-test 4 tree #'tree:split-frame-h #'tree:frame-width)))))

(fiasco:deftest poly-split-frame-horizontal-replaces-parent ()
  (with-border-box-mocks ()
    (let ((tree:*new-split-type* :many))
      (multiple-value-bind (tree container) (make-tree-for-tests)
        (multiple-value-bind (frame parent) (tree:split-frame-h tree)
          (declare (ignore frame))
          (is (find parent (tree:tree-children container) :test #'equal)))))))

(define-matrix binary-split-frame-vertical-retains-total-dimensions ((direction :bottom :top))
  (with-border-box-mocks ()
    (let ((tree:*new-split-type* :binary))
      (let ((tree (make-tree-for-tests :width 1020 :height 1023)))
        (multiple-value-bind (frame parent) (tree:split-frame-v tree :direction direction)
          (declare (ignore frame))
          (check-size 1023 (tree:tree-children parent) #'tree:frame-height))))))

(define-matrix binary-split-frame-horizontal-retains-total-dimensions ((direction :right :left))
  (with-border-box-mocks ()
    (let ((tree:*new-split-type* :binary))
      (let ((tree (make-tree-for-tests :width 1023 :height 1000)))
        (multiple-value-bind (frame parent) (tree:split-frame-h tree :direction direction)
          (declare (ignore frame))
          (check-size 1023 (tree:tree-children parent) #'tree:frame-width))))))

(fiasco:deftest binary-split-v-top-order ()
  (with-border-box-mocks ()
    (let ((tree (make-tree-for-tests)))
      (multiple-value-bind (new-frame new-parent) (tree:split-frame-v tree :direction :top)
        (is (equal new-frame (first (tree:tree-children new-parent))))))))

(fiasco:deftest binary-split-v-bottom-order ()
  (with-border-box-mocks ()
    (let ((tree (make-tree-for-tests)))
      (multiple-value-bind (new-frame new-parent) (tree:split-frame-v tree :direction :bottom)
        (is (equal new-frame (second (tree:tree-children new-parent))))))))

(fiasco:deftest binary-split-h-left-order ()
  (with-border-box-mocks ()
    (let ((tree (make-tree-for-tests)))
      (multiple-value-bind (new-frame new-parent) (tree:split-frame-h tree :direction :left)
        (is (equal new-frame (first (tree:tree-children new-parent))))))))

(fiasco:deftest binary-split-h-right-order ()
  (with-border-box-mocks ()
    (let ((tree (make-tree-for-tests)))
      (multiple-value-bind (new-frame new-parent) (tree:split-frame-h tree :direction :right)
        (is (equal new-frame (second (tree:tree-children new-parent))))))))

(defun check-children-dimensions (parent size-list accessor)
  (loop for c in (tree:tree-children parent)
        for size in size-list
        do
        (is (= size (funcall accessor c)))))

(define-matrix binary-split-h-child-sizing ((direction :left :right))
  (with-border-box-mocks ()
    (let ((tree (make-tree-for-tests :width 155 :height 255)))
      (multiple-value-bind (new-frame new-parent) (tree:split-frame-h tree :direction direction)
        (declare (ignore new-frame))
        (check-children-dimensions new-parent (list 77 78)
                                   #'tree:frame-width)))))

(define-matrix binary-split-v-child-sizing ((direction :top :bottom))
  (with-border-box-mocks ()
    (let ((tree (make-tree-for-tests :width 155 :height 255)))
      (multiple-value-bind (new-frame new-parent) (tree:split-frame-v tree :direction direction)
        (declare (ignore new-frame))
        (check-children-dimensions new-parent (list 128 127)
                                   #'tree:frame-height)))))

(defun split-frame-times (frame times split-fn)
  (with-border-box-mocks ()
    (multiple-value-bind (new-frame parent) (funcall split-fn frame)
      (declare (ignore new-frame))
      (dotimes (i (- times 1))
        (multiple-value-bind (new-frame new-parent) (funcall split-fn parent)
          (declare (ignore new-frame))
          (setf parent new-parent)))
      parent)))

(fiasco:deftest poly-split-h-child-sizing-right ()
  (with-border-box-mocks ()
    (let* ((tree:*new-split-type* :many)
           (parent (split-frame-times (make-tree-for-tests) 2
                                      (lambda (x)
                                        (mahogany/tree:split-frame-h x :direction :right)))))
      (check-children-dimensions parent
                                 (list 33 33 34) #'tree:frame-width))))

(fiasco:deftest poly-split-h-child-sizing-left ()
  (with-border-box-mocks ()
    (let* ((tree:*new-split-type* :many)
           (parent (split-frame-times (make-tree-for-tests) 2
                                      (lambda (x)
                                        (mahogany/tree:split-frame-h x :direction :left)))))
      (check-children-dimensions parent
                                 (list 34 33 33) #'tree:frame-width))))

(fiasco:deftest poly-split-v-child-sizing-right ()
  (with-border-box-mocks ()
    (let* ((tree:*new-split-type* :many)
           (parent (split-frame-times (make-tree-for-tests) 2
                                      (lambda (x)
                                        (mahogany/tree:split-frame-v x :direction :top)))))
      (check-children-dimensions parent
                                 (list 33 33 34) #'tree:frame-height))))

(fiasco:deftest poly-split-v-child-sizing-left ()
  (with-border-box-mocks ()
    (let* ((tree:*new-split-type* :many)
           (parent (split-frame-times (make-tree-for-tests) 2
                                      (lambda (x)
                                        (mahogany/tree:split-frame-v x :direction :bottom)))))
      (check-children-dimensions parent
                                 (list 34 33 33) #'tree:frame-height))))

(fiasco:deftest remove-frame-output-node-frame-next ()
  "Check that the frame-next pointer is updated correctly when an output node is removed."
  (with-border-box-mocks ()
    (multiple-value-bind (frame output-node)
        (make-tree-for-tests)
      (declare (ignore frame))
      (let* ((container (tree:frame-parent output-node))
             (output-node-2 (container-add-mock-output container)))
        (tree:remove-frame output-node-2)
        (is (eq (tree:frame-next output-node) (first (tree:tree-children output-node))))))))

(fiasco:deftest remove-frame-output-node-frame-prev ()
  "Check that the frame-prev pointer is updated correctly when an output node is removed."
  (with-border-box-mocks ()
    (multiple-value-bind (frame output-node)
        (make-tree-for-tests)
      (declare (ignore frame))
      (let* ((container (tree:frame-parent output-node))
	         (output-node-2 (container-add-mock-output container)))
        (tree:remove-frame output-node-2)
        (is (eq (tree:frame-prev output-node) (first (tree:tree-children output-node))))))))

(fiasco:deftest add-output-new-output-frame-next ()
  (with-border-box-mocks ()
    (multiple-value-bind (frame output-node)
        (make-tree-for-tests)
      (let* ((container (tree:frame-parent output-node))
             (output-node-2 (container-add-mock-output container)))
        (is (eq (tree:frame-next output-node-2) frame))))))

(fiasco:deftest add-output-split-right-frame-next ()
  (declare (optimize (debug 3) (speed 0)))
  (with-border-box-mocks ()
    (multiple-value-bind (frame output-node container)
        (make-tree-for-tests)
      (declare (ignore output-node))
      (let* ((new-frame (tree:split-frame-h frame :direction :left))
             (new-output (container-add-mock-output container))
             (next-frame (tree:frame-next new-output)))
        (is (eq next-frame new-frame))))))

(fiasco:deftest add-output-split-right-frame-prev ()
  (declare (optimize (debug 3) (speed 0)))
  (with-border-box-mocks ()
    (multiple-value-bind (frame output-node container)
        (make-tree-for-tests)
      (declare (ignore output-node))
      (let* ((new-frame (tree:split-frame-h frame :direction :right))
             (new-output (container-add-mock-output container))
             (prev-frame (tree:frame-prev new-output)))
        (is (eq prev-frame new-frame))))))

(defstruct (mock-view (:include hrt::view)
                      (:constructor make-mock-view (hrt-view))))

(fiasco:deftest find-view-finds-empty ()
  (with-border-box-mocks ()
    (let* ((view (make-mock-view (cffi:null-pointer))))
      (with-tree ((parent :split-direction :vertical)
                  (child-1 :x 0 :y 0 :width 100 :height 100 :view view)
                  (child-2 :x 100 :y 0 :width 100 :height 100))
        (is (eq (tree:find-view-frame parent nil) child-2))))))

(fiasco:deftest parent-frame-finds-view ()
  (with-border-box-mocks ()
    (let* ((view (make-mock-view (cffi:null-pointer))))
      (with-tree ((parent :split-direction :vertical)
                  (child-1 :x 0 :y 0 :width 100 :height 100)
                  (child-2 :view view :x 100 :y 0 :width 100 :height 100))
        (is (eq child-2 (tree:find-view-frame parent view)))))))

(fiasco:deftest remove-frame-output-node-fullscreen-calls-cleanup ()
  (with-border-box-mocks ()
    (cl-mock:dflet ((hrt:scene-create-fullscreen-node
                     (layer view output)
                     (declare (ignore layer view output))
                     (cffi:null-pointer)))
      (multiple-value-bind (frame output-node)
          (make-tree-for-tests)
        (declare (ignore frame))
        (let ((view (make-mock-view (cffi:null-pointer)))
              (visited nil))
          (tree:set-fullscreen output-node view)
          (tree:remove-frame output-node (lambda (x)
                                           (when (eq output-node x)
                                             (setf visited t))))
          (is visited))))))

(fiasco:deftest find-first-leaf-from-output-node ()
  (declare (optimize (debug 3) (speed 0)))
  (with-border-box-mocks ()
    (multiple-value-bind (frame output-node)
        (make-tree-for-tests)
      (let* ((new-frame (tree:split-frame-h frame :direction :left))
             (found (tree:find-first-leaf output-node)))
        (is (eq new-frame found))))))
