* Mahogany
  Mahogany is a tiling window manager for Wayland modeled after
  StumpWM. While it is not a drop-in replacement for stumpwm, stumpwm
  users should be very comfortable with Mahogany. Its planned
  features are:
  + Easy extensibility: through the use of different modes, users can
    modify keybindings present in Mahogany.
  + Module system that allows users to load and use code at their
    descretion.
  + Programs to interact with other running services such as
    pulseaudio and alsamixer, as well as facilities to controll screen
    brightness. These are module based, so they don't have to be
    loaded if your system doesn't use them.
  + Good support for floating windows.
  + A configuration system using Common Lisp.

  This branch contains a version of Mahogany using a backend written
  in C. The old version written entirely in Common Lisp can be found in
  the [[https://github.com/stumpwm/mahogany/tree/full-cl-old][full-cl-old]] branch.
** Building
   There are two parts to Mahogany that need to be compiled
   seperately: the backend written in C, and the Common Lisp front
   end. The CL front end has yet to be written.

*** Building the backend
    Requirements:
    + =wlroots=, as taken from this fork: [[https://github.com/sdilts/wlroots/tree/0.10.0-layer-shell][0.10.0-layer-shell]]
    + =xkbcommon=
    + =xcb=, if xwayland support is enabled

    Once the requirements are installed, build the backend found in
    the =heart= directory:
    #+BEGIN_SRC shell
    mkdir heart/build
    cd heart/build
    meson ..
    ninja
    #+END_SRC

    The test application can be ran with:
    #+BEGIN_SRC shell
    ./example/heart
    #+END_SRC
