* NOTE: there is nothing notable implemented yet.
* Mahogany
  Mahogany is a tiling window manager for Wayland modeled after
  stumpwm. While it is not a drop-in replacement for stumpwm, stumpwm
  users should be very comfortable with Mahogany. Its planned
  features are:
  + [ ] Easy extensibility: through the use of different modes, users can
    modify keybindings present in Mahogany, and even have different
    keybindings for each program or window.
  + [ ] Module system that allows users to load and use code at their
    descretion.
  + [ ] Programs to interact with other running services such as
    pulseaudio and alsamixer, as well as facilities to controll screen
    brightness. These are module based, so they don't have to be
    loaded if your system doesn't use them.
  + [ ] Good support for floating windows
  + [X] A Common Lisp code base.
** TODO Installation
   Currently, the only way to install Mahogany is to compile from
   source.
*** Requirements:
    These are the requirements that must be manually installed. For
    the lisp dependencies, it is enough to download the repositories
    to where they can be found by =asdf=, the lisp dependency manager. Either
    place them in =~/quicklisp/local-projects= once quicklisp is installed, or use
    one of the methods described in the [[https://common-lisp.net/project/asdf/asdf/Configuring-ASDF-to-find-your-systems.html][relevant section of the asdf manual]].
    + [[https://www.quicklisp.org/][Quicklisp]] for automatically installing some of the lisp
      dependencies. Folow the instructions listed at the link.
    + [[https://github.com/sdilts/cl-wayland][cl-wayland]]. As of the time of writing, the distribution included
      with quicklisp is not up to date with the latest changes. Use
      the devel branch of linked repository instead; it will always be
      up to date.
    + [[https://github.com/swaywm/wlroots][wlroots]] and [[https://github.com/swaywm/cl-wlroots][cl-wlroots]]. Install them per the directions in each project's
      readme. The submodule included in the cl-wlroots repository will always
      work, but may lag behind several commits. For all the features of Mahogany,
      ensure that XWayland support is included.
    + A lisp implementation that supports multithreading. ~SBCL~ is
      recommended, although it /should/ work with any implementation
      with a recent version of ~asdf~. Mahogany is tested
      with SBCL and CCL.
*** Instalation
    You can't currently install this project.
    Once the above dependencies are downloaded and are discoverable
    via quicklisp, run the usual ~configure~, ~make~ and ~make install~ commands.
** TODO Customizing Mahogany
** TODO Adding new features/modes
   Please see the [[./doc/devel/][documentation directory]] for details on how to extend
   Mahogany.
** TODO Contributing to Mahogany
