(in-package :mahogany/backend)

(defgeneric get-device-name (input-device)
  (:documentation "Get the name of the input device")
  (:method ((device input-device))
    (foreign-slot-value (input-device-wlr-input device)
			'(:struct wlr:input-device)
			:name)))

(defgeneric get-device-vendor (input-device)
  (:documentation "Get the device vendor id")
  (:method ((device input-device))
    (foreign-slot-value (input-device-wlr-input device)
			'(:struct wlr:input-device)
			:vendor)))

(defgeneric get-device-product (input-device)
  (:documentation "Get the device produce id")
  (:method ((device input-device))
    (foreign-slot-value (input-device-wlr-input device)
			'(:struct wlr:input-device)
			:product)))
