* Frame Tree

There are three general types of nodes in the frame tree:

+ Parent trees, represented by the =tree-frame= class
+ Leaf frames, represented by the =view-frame= class. These nodes
  contain application windows.
+ Output nodes, represented by the =output-node= class.

=tree-frame= objects are broken into two further categories:
+ =binary-tree-frame=, which represents a tree frame that always has
  two children.
+ =poly-tree-frame=, which represents a tree frame that has two or
  more children.

Each complete tree is grouped into a =tree-container=, which contains
one tree for each output that is currently visible.

The =output-node= class is the root of a frame tree, and has exactly
one child, which is the actual tree graph. This class is here so that
there is a fixed object that we can refer to when looking at the trees
in the =tree-container= class; otherwise, operations like
=replace-frame= and output manipulation become much more difficult to
implement; without this, there is no fixed node to refer to instead of
one that may be deleted or moved elsewhere in the tree.
